# Generated by Django 4.1 on 2022-08-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_md_content_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='summary_text',
            field=models.CharField(default='Summary text', max_length=500),
            preserve_default=False,
        ),
    ]
