# Generated by Django 4.1 on 2022-09-06 00:19

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_media_options_alter_media_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rendered_summary',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='rendered_text',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='md_content',
            field=markdownfield.models.MarkdownField(blank=True, null=True, rendered_field='rendered_text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary_text',
            field=markdownfield.models.MarkdownField(blank=True, null=True, rendered_field='rendered_summary'),
        ),
    ]
