# This is a basic workflow to help you get started with Actions

name: Deploy to Digital Ocean

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "django" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy Django
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd django
            git pull origin django
            .venv/bin/pip3 -q install --upgrade pip
            .venv/bin/pip3 -q install -r requirements.txt
            DJANGO_SETTINGS_MODULE=blogsite.settings.prod .venv/bin/python manage.py migrate
            DJANGO_SETTINGS_MODULE=blogsite.settings.prod .venv/bin/python manage.py collectstatic --no-input
            sudo systemctl restart gunicorn.service